import Head from "next/head";
// import { Inter } from "@next/font/google";
import blogData from "@/data/blogData";
import React, { useState } from "react";
import { Box, Typography, TextField, Chip } from "@mui/material";
import BlogData from "../types/types";
import useActiveCategory from "@/hooks/useActiveCategory";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import BlogPosts from "@/components/BlogPosts/BlogPosts";
import ChipFilters from "@/components/ChipFilters/ChipFilters";

// const inter = Inter({ subsets: ["latin"] });

export default function Blog() {
  // const [stableBlogData, setStableBlogData] = useState<BlogData>(blogData);
  const [blogPosts, setBlogPosts] = useState<BlogData>(blogData);
  const { activeCategory, handleCategoryButton } = useActiveCategory();
  const stableBlogData: BlogData = blogData;

  const filteredPostsByCategoryId = (id: number, name: string) => {
    console.log("Chosen ID", id);
    console.log("Filtered table", {
      posts: stableBlogData.posts.filter((post) =>
        post.categories.includes(id)
      ),
    });

    setBlogPosts((prevState) => ({
      ...prevState,
      posts: stableBlogData.posts.filter((post) =>
        post.categories.includes(id)
      ),
      categories: prevState.categories,
    }));

    handleCategoryButton(name);
  };

  const filteredPostsBySearchInput = (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    console.log(e.target.value);

    setBlogPosts((prevState) => ({
      ...prevState,
      posts: stableBlogData.posts.filter(({ title }) =>
        title.toLowerCase().includes(e.target.value.toLowerCase())
      ),
      categories: prevState.categories,
    }));
  };

  return (
    <>
      <Head>
        <title>Patryk Kwasek | Emersoft - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box className="max-w-screen-xl w-11/12 my-0 mx-auto">
          <Header />

          <Box>
            <Typography
              variant="h3"
              className="text-emersoft-green text-3xl font-bold mb-4 uppercase"
            >
              Hello, my name is Patryk
            </Typography>
            <Typography variant="h1" className="text-4xl lg:text-7xl font-bold">
              Emersoft README.md
            </Typography>

            <TextField
              type="search"
              // placeholder="Search in Readme..."
              placeholder="Search blog posts..."
              onChange={filteredPostsBySearchInput}
              className="w-full my-4"
            />

            <ChipFilters
              stableBlogData={stableBlogData}
              activeCategory={activeCategory}
              filteredPostsByCategoryId={filteredPostsByCategoryId}
            />

            {/* Display blog card item or No results found*/}
            <BlogPosts blogPosts={blogPosts} stableBlogData={stableBlogData} />
          </Box>
        </Box>

        <Footer />
      </main>
    </>
  );
}
